2022-11-11 15:33:55,048 - exc_logger - ERROR - exception in post
-------------------------                ------------------------------------------------
Traceback (most recent call last):
  File "/home/dell/blogproject/blogproject/apps/blog/logs.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/dell/blogproject/blogproject/apps/api_view/views.py", line 74, in post
    return Response({'token': token.key,"message": "Login Successfully",'user':username},
AttributeError: 'tuple' object has no attribute 'key'
2022-11-11 15:34:31,776 - exc_logger - ERROR - exception in post
-------------------------                ------------------------------------------------
Traceback (most recent call last):
  File "/home/dell/blogproject/blogproject/apps/blog/logs.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/dell/blogproject/blogproject/apps/api_view/views.py", line 74, in post
    return Response({'token': token.key,"message": "Login Successfully",'user':username},
AttributeError: 'tuple' object has no attribute 'key'
2022-11-11 15:40:51,751 - exc_logger - ERROR - exception in post
-------------------------                ------------------------------------------------
Traceback (most recent call last):
  File "/home/dell/blogproject/blogproject/apps/blog/logs.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/dell/blogproject/blogproject/apps/api_view/views.py", line 74, in post
    return Response({'token': token.key,"message": "Login Successfully",'user':username},
AttributeError: 'tuple' object has no attribute 'key'
2022-12-14 15:57:33,675 - exc_logger - ERROR - exception in post
-------------------------                ------------------------------------------------
Traceback (most recent call last):
  File "/home/dell/blogproject/blogproject/apps/blog/logs.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/dell/blogproject/blogproject/apps/api_view/views.py", line 74, in post
    return Response({'token': token.key,"message": "Login Successfully",'user':username},
AttributeError: 'tuple' object has no attribute 'key'
2022-12-14 16:01:31,977 - exc_logger - ERROR - exception in post
-------------------------                ------------------------------------------------
Traceback (most recent call last):
  File "/home/dell/blogproject/blogproject/apps/blog/logs.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/dell/blogproject/blogproject/apps/api_view/views.py", line 74, in post
    return Response({'token': token.key,"message": "Login Successfully",'user':username},
AttributeError: 'tuple' object has no attribute 'key'
2022-12-14 16:04:45,660 - exc_logger - ERROR - exception in post
-------------------------                ------------------------------------------------
Traceback (most recent call last):
  File "/home/dell/blogproject/blogproject/apps/blog/logs.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/dell/blogproject/blogproject/apps/api_view/views.py", line 74, in post
    return Response({'token': token.key,"message": "Login Successfully",'user':username},
AttributeError: 'tuple' object has no attribute 'key'
2022-12-14 16:04:52,085 - exc_logger - ERROR - exception in post
-------------------------                ------------------------------------------------
Traceback (most recent call last):
  File "/home/dell/blogproject/blogproject/apps/blog/logs.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/dell/blogproject/blogproject/apps/api_view/views.py", line 74, in post
    return Response({'token': token.key,"message": "Login Successfully",'user':username},
AttributeError: 'tuple' object has no attribute 'key'
